import { Tool } from '../tools';

export const WRITING_TOOLS: Tool[] = [
    {
        id: 'grammar-checker',
        title: 'Grammar Checker',
        description: 'Fix grammar, spelling, and punctuation errors instantly.',
        iconName: 'Languages',
        category: 'AI',
        href: '/ai/grammar-checker',
        type: 'text-to-text',
        seoTitle: 'Grammar Checker - Free Online Spell Check (Free)',
        seoDescription: 'Improve your writing quality with our AI-powered proofreader.',
        keywords: ['Grammar Checker', 'Spell Check', 'Proofreader'],
        content: {
            title: 'How to use AI Grammar Checker',
            description: 'Advanced AI analysis for professional writing.',
            steps: ['Paste text', 'Analyze', 'Fix errors'],
            features: ['Context-aware', 'Style tips', 'Free']
        }
    },
    {
        id: 'ai-paraphraser',
        title: 'AI Paraphraser',
        description: 'Rewrite sentences and paragraphs to improve clarity and tone.',
        iconName: 'Sparkles',
        category: 'AI',
        href: '/ai/paraphraser',
        type: 'text-to-text',
        seoTitle: 'AI Paraphraser - Sentence Rewriter Online (Free)',
        seoDescription: 'Rewrite content in various tones: Professional, Creative, Fluent.',
        keywords: ['AI Paraphraser', 'Sentence Rewriter', 'Rewrite Text'],
        content: {
            title: 'How to use AI Paraphraser',
            description: 'Transform your writing into a masterpiece.',
            steps: ['Enter content', 'Select tone', 'Rephrase'],
            features: ['Plagiarism safe', 'Natural output', 'Fast']
        }
    },
    {
        id: 'ai-content-detector',
        title: 'AI Content Detector',
        description: 'Check if a piece of text was generated by AI like ChatGPT.',
        iconName: 'Sparkles',
        category: 'AI',
        href: '/ai/content-detector',
        type: 'text-to-text',
        seoTitle: 'AI Content Detector - GPT-4 & ChatGPT Checker (Free)',
        seoDescription: 'Accurately identify machine-generated text in seconds.',
        keywords: ['AI Detector', 'ChatGPT Checker', 'AI Content Check'],
        content: {
            title: 'How to detect AI Content',
            description: 'Identify AI-generated patterns in your documents.',
            steps: ['Paste text', 'Scan', 'Review AI score'],
            features: ['Deep analysis', 'Supports GPT-4', 'Fast']
        }
    },
    {
        id: 'sentence-expander',
        title: 'Sentence Expander',
        description: 'Add depth and detail to your short sentences using AI.',
        iconName: 'Sparkles',
        category: 'AI',
        href: '/ai/sentence-expander',
        type: 'text-to-text',
        seoTitle: 'Sentence Expander - Write More with AI (Free)',
        seoDescription: 'Flesh out your ideas into comprehensive paragraphs.',
        keywords: ['Sentence Expander', 'Elaborate Text', 'Content Expander'],
        content: {
            title: 'How to Expand Sentences',
            description: 'Turn brief notes into well-explained concepts.',
            steps: ['Paste short text', 'Expand', 'Copy results'],
            features: ['Creative flow', 'Fast', 'Free']
        }
    },
    {
        id: 'text-summarizer',
        title: 'Text Summarizer',
        description: 'Condense long articles and documents into key bullet points.',
        iconName: 'FileText',
        category: 'AI',
        href: '/ai/summarizer',
        type: 'text-to-text',
        seoTitle: 'Text Summarizer - TL;DR Generator Online (Free)',
        seoDescription: 'Get the main points of any text instantly.',
        keywords: ['Text Summarizer', 'Summarize Article', 'TL;DR'],
        content: {
            title: 'How to Summarize Text',
            description: 'Save hours of reading with AI-driven summaries.',
            steps: ['Paste long text', 'Select length', 'Summarize'],
            features: ['Key points focus', 'Fast', 'Accurate']
        }
    },
    {
        id: 'essay-writer',
        title: 'AI Essay Writer',
        description: 'Generate essay drafts and outlines on any topic.',
        iconName: 'PenTool',
        category: 'AI',
        href: '/ai/essay-writer',
        type: 'text-to-text',
        seoTitle: 'AI Essay Writer - Generate Academic Drafts (Free)',
        seoDescription: 'Overcome writer\'s block with structured essay assistance.',
        keywords: ['AI Essay Writer', 'Essay Generator', 'Writing Assistant'],
        content: {
            title: 'How to use AI Essay Writer',
            description: 'Get structured arguments and creative ideas for your papers.',
            steps: ['Enter topic', 'Select structure', 'Generate'],
            features: ['Unique content', 'Structured flow', 'Fast']
        }
    },
    {
        id: 'title-generator',
        title: 'Title Generator',
        description: 'Create catchy titles for blogs, videos, and essays.',
        iconName: 'Sparkles',
        category: 'AI',
        href: '/ai/title-generator',
        type: 'text-to-text',
        seoTitle: 'Title Generator - Viral Headline Maker (Free)',
        seoDescription: 'Get dozens of headline ideas for your content.',
        keywords: ['Title Generator', 'Headline Maker', 'Blog Titles'],
        content: {
            title: 'How to Generate Catchy Titles',
            description: 'Maximize clicks with headlines optimized for engagement.',
            steps: ['Enter keywords', 'Generate', 'Pick the best title'],
            features: ['SEO optimized', 'Creative', 'Fast']
        }
    },
    {
        id: 'word-counter',
        title: 'Word Counter',
        description: 'Count words, characters, and reading time of your text.',
        iconName: 'FileText',
        category: 'Writing',
        href: '/writing/word-counter',
        type: 'text-to-text',
        seoTitle: 'Word Counter - Character & Word Tool Online (Free)',
        seoDescription: 'Real-time writing statistics for your documents.',
        keywords: ['Word Counter', 'Character Count', 'Reading Time'],
        content: {
            title: 'How to use Word Counter',
            description: 'Professional statistics for your writing projects.',
            steps: ['Type or paste text', 'See live stats', 'Download report'],
            features: ['Live updates', 'Advanced stats', 'Fast']
        }
    },
    {
        id: 'case-converter',
        title: 'Case Converter',
        description: 'Change text case: UPPERCASE, lowercase, Title Case, and more.',
        iconName: 'Languages',
        category: 'Writing',
        href: '/writing/case-converter',
        type: 'text-to-text',
        seoTitle: 'Case Converter - Online Text Formatter (Free)',
        seoDescription: 'Fix messy text formatting instantly with one click.',
        keywords: ['Case Converter', 'Title Case', 'Uppercase to Lowercase'],
        content: {
            title: 'How to Convert Text Case',
            description: 'Standardize your capitalization in seconds.',
            steps: ['Paste text', 'Select case type', 'Copy result'],
            features: ['Title Case support', 'Fast', 'Free']
        }
    },
    {
        id: 'remove-line-breaks',
        title: 'Remove Line Breaks',
        description: 'Cleanup broken text by removing unnecessary line breaks.',
        iconName: 'FileText',
        category: 'Writing',
        href: '/writing/remove-line-breaks',
        type: 'text-to-text',
        seoTitle: 'Remove Line Breaks - Clean Text Flow (Free)',
        seoDescription: 'Merge fragmented lines into clean paragraphs.',
        keywords: ['Remove Line Breaks', 'Clean Text', 'Paragraph Fixer'],
        content: {
            title: 'How to Remove Line Breaks',
            description: 'Fix the formatting of text copied from PDFs/Emails.',
            steps: ['Paste text', 'Process', 'Copy results'],
            features: ['Smart merging', 'Fast', 'Universal']
        }
    },
    {
        id: 'lorem-ipsum-generator',
        title: 'Lorem Ipsum Generator',
        description: 'Generate placeholder text for design and development.',
        iconName: 'FileText',
        category: 'Utility',
        href: '/utility/lorem-ipsum',
        type: 'text-to-text',
        seoTitle: 'Lorem Ipsum Generator - Placeholder Text Maker',
        seoDescription: 'Generate classic filler text for your mockups.',
        keywords: ['Lorem Ipsum', 'Filler Text', 'Placeholder Text'],
        content: {
            title: 'How to Generate Lorem Ipsum',
            description: 'Standard dummy text for the design industry.',
            steps: ['Select length', 'Generate', 'Copy'],
            features: ['Paragraph control', 'Fast', 'Free']
        }
    },
    {
        id: 'text-to-speech',
        title: 'Text to Speech (Browser)',
        description: 'Convert text to spoken audio using your browser\'s native API.',
        iconName: 'Languages',
        category: 'AI',
        href: '/ai/text-to-speech',
        type: 'text-to-text',
        seoTitle: 'Text to Speech - Online Audio Reader (Free)',
        seoDescription: 'Listen to your text with natural-sounding voices.',
        keywords: ['Text to Speech', 'Audio Reader', 'Listen to Text'],
        content: {
            title: 'How to use Text to Speech',
            description: 'Narrate your documents using built-in browser voices.',
            steps: ['Paste text', 'Select voice', 'Play audio'],
            features: ['Local playback', 'Multiple voices', 'Fast']
        }
    },
    {
        id: 'markdown-to-html',
        title: 'Markdown to HTML',
        description: 'Convert markdown text to clean HTML code.',
        iconName: 'FilePlus',
        category: 'Utility',
        href: '/utility/markdown-to-html',
        type: 'text-to-text',
        seoTitle: 'Markdown to HTML - Instant Web Converter (Free)',
        seoDescription: 'Turn .md files into web-ready HTML snippets.',
        keywords: ['Markdown to HTML', 'MD to HTML', 'Web Snippets'],
        content: {
            title: 'How to Convert Markdown to HTML',
            description: 'Efficient translation from markdown to coded HTML.',
            steps: ['Enter markdown', 'Convert', 'Copy HTML'],
            features: ['Clean output', 'Fast', 'No install']
        }
    },
    {
        id: 'ai-story-generator',
        title: 'AI Story Generator',
        description: 'Create unique creative stories and fictional plotlines.',
        iconName: 'PenTool',
        category: 'AI',
        href: '/ai/story-generator',
        type: 'text-to-text',
        seoTitle: 'AI Story Generator - Write Fiction Online (Free)',
        seoDescription: 'Get instant inspiration for your next novel or short story.',
        keywords: ['Story Generator', 'Plot Maker', 'Writing Prompts'],
        content: {
            title: 'How to Write a Story with AI',
            description: 'Infinite creative possibilities for fiction writers.',
            steps: ['Enter genre/theme', 'Generate plot', 'Copy story'],
            features: ['Creative prompts', 'Unique narratives', 'Fast']
        }
    },
    {
        id: 'ai-slogan-generator',
        title: 'AI Slogan Generator',
        description: 'Generate catchy slogans and taglines for your brand.',
        iconName: 'Sparkles',
        category: 'AI',
        href: '/ai/slogan-generator',
        type: 'text-to-text',
        seoTitle: 'Slogan Generator - Creative Brand Taglines (Free)',
        seoDescription: 'Dozens of business slogan ideas in one click.',
        keywords: ['Slogan Generator', 'Tagline Maker', 'Business Slogans'],
        content: {
            title: 'How to Generate Catchy Slogans',
            description: 'Make your brand memorable with AI taglines.',
            steps: ['Enter business name', 'Generate', 'Pick your favorite'],
            features: ['Brand focused', 'Creative', 'Instant']
        }
    }
];
